name: annomate-cuda
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pyside6>=6.11.0
  - opencv
  - numpy>=1.24.0
  - scipy>=1.10.0
  - matplotlib>=3.7.0
  - pillow>=10.0.0
  - pyinstaller
  - pytorch>=2.0.0
  - torchvision>=0.15.0
  - pytorch-cuda=11.8
  - pip
  - pip:
      - anomalib>=2.2.0
      - lightning>=2.0.0